<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>c02f7170-9636-439b-a458-172e0405eaaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navigation-fd3cee8df8']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cmp-navigation__item-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63239ca6-4a44-497a-9043-d08ace3fa986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/luma/us/en/experience.html</value>
      <webElementGuid>3047fa62-3bfa-4376-9bc6-a76048fde1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-navigation__item-link</value>
      <webElementGuid>8fc13ccf-68a7-4548-b100-944289e3432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>06684c7e-c2c7-44da-94a7-7a0db6894369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-fd3cee8df8&quot;)/ul[@class=&quot;cmp-navigation__group&quot;]/li[@class=&quot;cmp-navigation__item cmp-navigation__item--level-0&quot;]/a[@class=&quot;cmp-navigation__item-link&quot;]</value>
      <webElementGuid>0763fdfd-131a-4273-a0e9-2c83d976eb64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation-fd3cee8df8']/ul/li/a</value>
      <webElementGuid>54ef68ce-9c6d-4292-b216-28721e4c8e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>e5537fb5-b4ce-4b47-a071-ec2ffa9d6da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/content/luma/us/en/experience.html')]</value>
      <webElementGuid>fdaad642-5d31-4a17-960f-819e8a87a5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a</value>
      <webElementGuid>93c03cf6-56de-4fcc-843b-e1b4c7180ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/luma/us/en/experience.html' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>629f5ce0-a92c-44be-b7e4-61be43b54b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
