<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Men</name>
   <tag></tag>
   <elementGuidId>845a3ae9-6076-4807-bf94-3d826c135e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navigation-fd3cee8df8']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5758c7a-5796-41ff-b0ee-e42928fea1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/luma/us/en/men.html</value>
      <webElementGuid>ff5a0f6c-0824-4890-8cd6-e08746c69179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-navigation__item-link</value>
      <webElementGuid>445f4a29-9a11-4ba3-bef1-bcd144f27d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men</value>
      <webElementGuid>2368b472-d285-4f57-92dc-40837701ee91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-fd3cee8df8&quot;)/ul[@class=&quot;cmp-navigation__group&quot;]/li[@class=&quot;cmp-navigation__item cmp-navigation__item--level-0&quot;]/a[@class=&quot;cmp-navigation__item-link&quot;]</value>
      <webElementGuid>3d6c14b3-e08e-4257-bd51-994b42089b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation-fd3cee8df8']/ul/li[2]/a</value>
      <webElementGuid>d212923e-74b7-4679-ab8d-7e7a47db9ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Men')]</value>
      <webElementGuid>b1b7b5ae-3be1-4e1b-a358-107ad204637e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/content/luma/us/en/men.html')]</value>
      <webElementGuid>8a61edd8-e011-4472-a17c-4045bbde9cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>5c09fa9e-630b-4013-b7c3-fd9ed6dd76d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/luma/us/en/men.html' and (text() = 'Men' or . = 'Men')]</value>
      <webElementGuid>71637263-512f-4f00-93bf-ab9bdd829982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
