<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Women</name>
   <tag></tag>
   <elementGuidId>66a26141-fbd0-47ca-be94-6aeb001d3500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navigation-fd3cee8df8']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>126d519c-1773-4b79-ad8b-cde9eda0d6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/content/luma/us/en/women.html</value>
      <webElementGuid>2968f136-1714-43ba-87bd-b1dd9932a974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-navigation__item-link</value>
      <webElementGuid>614e7d56-8a66-4e84-aaaa-d8a6a6318ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>b7297f00-f163-4944-96de-7c48c1c5a67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-fd3cee8df8&quot;)/ul[@class=&quot;cmp-navigation__group&quot;]/li[@class=&quot;cmp-navigation__item cmp-navigation__item--level-0&quot;]/a[@class=&quot;cmp-navigation__item-link&quot;]</value>
      <webElementGuid>c641c676-eeb9-4343-8962-695400718c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation-fd3cee8df8']/ul/li[3]/a</value>
      <webElementGuid>d1f06db8-a8c5-4ed8-88c7-d114383c5ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Women')]</value>
      <webElementGuid>62dbfb4f-6373-454f-b392-faf6a766fdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/content/luma/us/en/women.html')]</value>
      <webElementGuid>9d5dab3b-23d5-4220-a125-18001dfd40af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>8c85b6f2-8100-4970-8633-4d8d3cf7b9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/content/luma/us/en/women.html' and (text() = 'Women' or . = 'Women')]</value>
      <webElementGuid>ca149451-7995-461c-bb3c-055d8d7292f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
