<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Books</name>
   <tag></tag>
   <elementGuidId>82febf97-3b3d-47a3-b15e-39a2e8484d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Books')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>204aab70-ed06-4241-8952-8dc2375ae011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/books</value>
      <webElementGuid>7a2a26d1-5a67-4839-bcce-13b76682cf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>bdd7e001-09c2-4dcd-9ed6-295774ca3a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books
        </value>
      <webElementGuid>cbaee922-cf3c-4630-a79e-83e187bbceb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;header-menu&quot;]/ul[@class=&quot;top-menu&quot;]/li[1]/a[@class=&quot;hover&quot;]</value>
      <webElementGuid>af1273c3-f5e6-41cf-ae1f-7fb4f3b3e403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Books')]</value>
      <webElementGuid>eb59bc94-5fa7-49db-81d0-7833bf57807c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/books')]</value>
      <webElementGuid>820b9cb6-0a41-49c7-9774-50f08075a5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>2404b5b9-2b5e-4f62-b0ce-8ea58de8101b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/books' and (text() = 'Books
        ' or . = 'Books
        ')]</value>
      <webElementGuid>893c71ad-801a-46c9-afab-27c3156638c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
