<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jewelry</name>
   <tag></tag>
   <elementGuidId>a8e42300-31f4-46de-951d-516c586f46e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Jewelry')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62805b4f-c3ef-483b-b8a8-90173112741b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jewelry</value>
      <webElementGuid>d322ed97-6fa8-4bad-b37c-c908d2b7551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>2f6b2a08-2f71-4159-8090-20534a5ccc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jewelry
        </value>
      <webElementGuid>33432617-8443-47a5-84f7-298d8354daa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;header-menu&quot;]/ul[@class=&quot;top-menu&quot;]/li[6]/a[@class=&quot;hover&quot;]</value>
      <webElementGuid>f0bf4a04-fdcd-4bbb-8b81-36c6aeedbf6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jewelry')]</value>
      <webElementGuid>d1b4a518-aaf9-416d-a12c-990c7d168799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jewelry')]</value>
      <webElementGuid>19de8e37-6603-4f1f-bbd6-1f82dee0771e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>2f34dbef-0396-48ed-b1c4-be0ce0860b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jewelry' and (text() = 'Jewelry
        ' or . = 'Jewelry
        ')]</value>
      <webElementGuid>e26e0dc9-7d15-4f10-a220-4a8b22051479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
