<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wishlist</name>
   <tag></tag>
   <elementGuidId>1929479a-b7ba-43c5-a80c-3f71a25f684c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Wishlist')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.ico-wishlist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31273da9-2cd2-4e6f-ae1f-dfdf68a49455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wishlist</value>
      <webElementGuid>9088be2e-c404-45e6-b322-c15d1c5c1346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-wishlist</value>
      <webElementGuid>f85aab95-3c6a-4189-abb6-7289d724cca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wishlist</value>
      <webElementGuid>b529732f-702e-4160-828a-ef745e231e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;footer-menu-wrapper&quot;]/div[@class=&quot;column my-account&quot;]/ul[1]/li[5]/a[@class=&quot;ico-wishlist&quot;]</value>
      <webElementGuid>ec6859a1-9134-4ffa-92ca-4c9d4e0863dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wishlist')]</value>
      <webElementGuid>b9778122-1723-407c-882a-b4f91853c4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wishlist')])[2]</value>
      <webElementGuid>d97bac52-e0a8-4d92-bd74-512773003890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[5]/a</value>
      <webElementGuid>578380f8-37df-4843-8891-466257baa6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wishlist' and (text() = 'Wishlist' or . = 'Wishlist')]</value>
      <webElementGuid>1c04a992-ea2b-4800-a9ea-6faff014979a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
