<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_YouTube</name>
   <tag></tag>
   <elementGuidId>8b1a79c7-4e04-4dba-a34f-c7618f1ea78e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'YouTube')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.youtube > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58b6f9cf-22b4-49f6-a9a1-8a7db9d94508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.youtube.com/user/nopCommerce</value>
      <webElementGuid>40ddcde9-609f-4136-8d95-39c69cca6162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>33501ad0-b94e-4d78-a1b8-d535d3b2896b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YouTube</value>
      <webElementGuid>6125668f-da1a-443c-b979-80d0b6d5ab01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;footer&quot;]/div[@class=&quot;footer-menu-wrapper&quot;]/div[@class=&quot;column follow-us&quot;]/ul[1]/li[@class=&quot;youtube&quot;]/a[1]</value>
      <webElementGuid>a0285f96-8062-4e2d-bbfe-ad8023346ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'YouTube')]</value>
      <webElementGuid>70d0ae01-55e5-467e-9064-c02d02425d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.youtube.com/user/nopCommerce']</value>
      <webElementGuid>88428554-26cf-474b-ab2e-13e45fd635b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[4]/a</value>
      <webElementGuid>514c8797-0f22-49d3-8023-462ebc31dfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.youtube.com/user/nopCommerce' and (text() = 'YouTube' or . = 'YouTube')]</value>
      <webElementGuid>b7f598a9-5790-4199-acf1-b2439a44e83f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
