<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_q</name>
   <tag></tag>
   <elementGuidId>0a53e367-a61e-439b-b4c8-984e845083cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#small-searchterms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='small-searchterms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5718d584-bb42-49b2-8b79-1dfd0721bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aef0ffb4-b9f0-4a90-9a79-1b4d32f3ba55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box-text ui-autocomplete-input</value>
      <webElementGuid>c65ada46-f370-4ca2-aee0-d407c3edf9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>small-searchterms</value>
      <webElementGuid>3f34d145-b644-42be-b230-e44eb8cc42e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7bef8a58-dc48-47b0-8b51-9b85f1c04bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search store</value>
      <webElementGuid>b4d03e51-b4aa-4a0c-945d-0fad7b96b740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>6e439fdc-cde9-4982-a709-eb8e162df0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;small-searchterms&quot;)</value>
      <webElementGuid>61ef9cca-6956-4729-a27b-0267a13218de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='small-searchterms']</value>
      <webElementGuid>749332bd-9c22-4bae-98a0-3a5426a4087c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>724aaf40-4c0c-4b22-bccd-b2846bc7091e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'small-searchterms' and @name = 'q']</value>
      <webElementGuid>fc5a1028-0650-49e7-9cfd-fa33431dd745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
