<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spandemo_username_label</name>
   <tag></tag>
   <elementGuidId>c6d5f096-06c5-4ac2-a7eb-04acd5951c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#demo_username_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='demo_username_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbfabfc7-f4ad-44e9-8fcc-580c8acd9e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon</value>
      <webElementGuid>db955bb9-6b1a-4314-81cc-000ad284b8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo_username_label</value>
      <webElementGuid>78d851d5-57b3-4a47-b977-d8b8d6dd74fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo_username_label&quot;)</value>
      <webElementGuid>fde32356-84b5-48dc-93aa-c49d5db7339b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='demo_username_label']</value>
      <webElementGuid>fcf05db7-2473-46e4-80b4-ffed139cd46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='login']/div/div/div[2]/form/div/div/div/div/span</value>
      <webElementGuid>3ab484eb-a0d6-4be2-b8f0-fe4c8d6151ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>dbc01899-a567-460e-ab67-e6f1b86de2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'demo_username_label']</value>
      <webElementGuid>e4d9c2ea-b4ef-4546-905a-3fde5adb1283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
